# Generated by Django 4.2.22 on 2025-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_components_price_components_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='components',
            field=models.ManyToManyField(blank=True, to='base.components'),
        ),
        migrations.AddField(
            model_name='order',
            name='components_details',
            field=models.ManyToManyField(blank=True, to='base.cps_details'),
        ),
    ]
