# Generated by Django 4.2.23 on 2025-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_address_remove_cps_details_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_quick',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
