# Generated by Django 4.2.23 on 2025-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='order',
            name='full_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
