# Generated by Django 4.2.23 on 2025-08-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_is_quick_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
