# Generated by Django 4.2.23 on 2025-08-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
        migrations.AlterField(
            model_name='orderimages',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
    ]
